##########################################
# PARAMÈTRES GÉNÉRAUX
##########################################
[event]
name = "Championnat de France de parties rapides"
update_password = "mdp"
css = "ffe/ffe.css"

[tournament.principal] 
name = "France rapide 2023"
ffe_id = 58698
ffe_password = "LUEOLGWAAA"

[template.alpha]
type = "players"
columns = 2
show_timer = false
menu = "family"
menu_text = "[%f-%l]"
[template.alpha.players]
tournament = "principal"
part = "?"
parts = 12
name = "Appariements de %f à %l"

[family.alpha]
template = "alpha"
range = "1-12"

[template.saisie]
type = "boards"
update = true
columns = 2
show_timer = true
menu = "family"
menu_text = "Echiquiers %f-%l"
[template.saisie.boards]
tournament = "principal"
part = "?"
parts = 6
name = "Echiquiers %f à %l"

[family.saisie]
template = "saisie"
range = "1-6"

[template.affichage]
type = "boards"
update = false
columns = 2
show_timer = true
menu = "family"
menu_text = "Echiquiers %f-%l"
[template.affichage.boards]
tournament = "principal"
part = "?"
parts = 6
name = "Echiquiers %f à %l"

[family.affichage]
template = "affichage"
range = "1-6"

[screen.resultats]
type = "results"
columns = 2
show_timer = true
limit = 30
menu = "none"
menu_text = "Dernier résultats"

[rotator.alpha]
delay = 15
families = "alpha"

[timer.hour.pointage]
date = 2023-06-25T09:00:00
text_before = "Fin du pointage dans %s"
text_after = "Pointage terminé depuis %s"
[timer.hour.1]
date = 09:30:00
[timer.hour.2]
date = 10:15:00
[timer.hour.3]
date = 11:00:00
[timer.hour.4]
date = 11:45:00
[timer.hour.5]
date = 13:30:00
[timer.hour.6]
date = 14:15:00
[timer.hour.7]
date = 15:00:00
[timer.hour.8]
date = 15:45:00
[timer.hour.9]
date = 16:30:00
[timer.hour.remise-des-prix]
date = 17:15:00
text_before = "Remise des prix dans %s"
text_after = "Remise des prix commencée depuis %s"
